# .github/workflows/ci.yml
name: C++ CI

on: [ push, pull_request ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y g++ make

    - name: Build with Make
      run: make

    - name: Run executableca
      run: ./calculator
